### ISSUE TITLE
Issues on Ubuntu 22.04 after installing 5.11.1

### ISSUE THREAD

**Issue by davidstevenrojas** [telerik/fiddler-everywhere#23]
**Describe the bug**
When you open FIddler 5.11.1 and open the settings screen, the UI becomes almost unusable, you can't browse the menus from the settings. When you close it, you can no longer inspect request details on the Live Traffic window. I noticed an error is shown in the netcore.log:

[2024-06-16 08:05:59:966] [Information] [NETCore] Initializing settings service.
[2024-06-16 08:06:00:018] [Information] [NETCore] Ensuring latest settings.
[2024-06-16 08:06:00:019] [Critical] [Angular] Cannot read properties of undefined (reading 'theme')
[2024-06-16 08:06:00:020] [Critical] [Angular] TypeError: Cannot read properties of undefined (reading 'theme')     at tt.setAndApplyTheme (file:///tmp/.mount_fiddleVcHl9Q/resources/app/out/WebServer/ClientApp/dist/main.b7319ee8e762c1bd.js:1:452025)     at z._next (file:///tmp/.mount_fiddleVcHl9Q/resources/app/out/WebServer/ClientApp/dist/main.b7319ee8e762c1bd.js:1:450684)     at z.__tryOrUnsub (file:///tmp/.mount_fiddleVcHl9Q/resources/app/out/WebServer/ClientApp/dist/main.b7319ee8e762c1bd.js:1:2720257)     at z.next (file:///tmp/.mount_fiddleVcHl9Q/resources/app/out/WebServer/ClientApp/dist/main.b7319ee8e762c1bd.js:1:2719486)     at N._next (file:///tmp/.mount_fiddleVcHl9Q/resources/app/out/WebServer/ClientApp/dist/main.b7319ee8e762c1bd.js:1:2718662)     at N.next (file:///tmp/.mount_fiddleVcHl9Q/resources/app/out/WebServer/ClientApp/dist/main.b7319ee8e762c1bd.js:1:2718436)     at L._next (file:///tmp/.mount_fiddleVcHl9Q/resources/app/out/WebServer/ClientApp/dist/main.b7319ee8e762c1bd.js:1:2740919)     at L.next (file:///tmp/.mount_fiddleVcHl9Q/resources/app/out/WebServer/ClientApp/dist/main.b7319ee8e762c1bd.js:1:2718436)     at L._next (file:///tmp/.mount_fiddleVcHl9Q/resources/app/out/WebServer/ClientApp/dist/main.b7319ee8e762c1bd.js:1:2740047)     at L.next (file:///tmp/.mount_fiddleVcHl9Q/resources/app/out/WebServer/ClientApp/dist/main.b7319ee8e762c1bd.js:1:2718436)

 - Used Operating System: Ubuntu Release 22.04.4 LTS (Jammy Jellyfish) 64-bit
 - Affected Fiddler UI Settings screen opening, after this, the whole app is affected
 - Affected functionality settings inspection triggers the issue
 - 
**To Reproduce**
1. Go to settings
2. Click on any available menu: Connections, Gateway, Live Traffic, etc
3. The settings from each selected option won't load
4. See error in the netcore.log
5. Close the settings screen
6. Try to inspect details for any request on the live traffic window: they wont load anymore.

**Expected behavior**
The settings should load and allow me to change them without any issues

**Screenshots**
Attached is a video

**Additional context**
Also attached the log file

https://github.com/telerik/fiddler-everywhere/assets/1041144/03a02595-da7b-427b-9cb8-35e59dd697b9
[netcore.log.zip](https://github.com/user-attachments/files/15858118/netcore.log.zip)

**Comment by NickIliev** [comment]
@davidstevenrojas 

Try the following:

1. Close the Fiddler Everywhere application
2. Delete the following directory
  ```
   ~/.config/Fiddler Everywhere/
  ```
3. Start and re-test the application's UI.

If the above does not resolve the issue, you can delete the main Fiddler directory. Note that this directory holds any locally stored saved session snapshots, composer's request collections, etc. If needed, you can create a cloud backup before deleting the directory to avoid the loss of information.

1. Close the Fiddler Everywhere application
2. Delete the following directory
  ```
   ~/.fiddler/
  ```
3. Start and re-test the application's UI.

**Comment by davidstevenrojas** [comment]
Removing the  ~/.fiddler/ folder did it. Thanks!
